''' <summary>
''' ClamAV engine field.
''' </summary>
''' <remarks>Please read ClamAV's documentation for more information.</remarks>
<Flags()>
Public Enum ClamEngineField

    CL_ENGINE_MAX_SCANSIZE

    CL_ENGINE_MAX_FILESIZE

    CL_ENGINE_MAX_RECURSION

    CL_ENGINE_MAX_FILES

    CL_ENGINE_MIN_CC_COUNT

    CL_ENGINE_MIN_SSN_COUNT

    CL_ENGINE_PUA_CATEGORIES

    CL_ENGINE_DB_OPTIONS

    CL_ENGINE_DB_VERSION

    CL_ENGINE_DB_TIME

    CL_ENGINE_AC_ONLY

    CL_ENGINE_AC_MINDEPTH

    CL_ENGINE_AC_MAXDEPTH

    CL_ENGINE_TMPDIR

    CL_ENGINE_KEEPTMP

    CL_ENGINE_BYTECODE_SECURITY

    CL_ENGINE_BYTECODE_TIMEOUT

    CL_ENGINE_BYTECODE_MODE

    CL_ENGINE_MAX_EMBEDDEDPE

    CL_ENGINE_MAX_HTMLNORMALIZE

    CL_ENGINE_MAX_HTMLNOTAGS

    CL_ENGINE_MAX_SCRIPTNORMALIZE

    CL_ENGINE_MAX_ZIPTYPERCG

    CL_ENGINE_FORCETODISK

    CL_ENGINE_DISABLE_CACHE

    CL_ENGINE_DISABLE_PE_STATS

    CL_ENGINE_STATS_TIMEOUT

    CL_ENGINE_MAX_PARTITIONS

    CL_ENGINE_MAX_ICONSPE

    CL_ENGINE_TIME_LIMIT
End Enum

